name: exa2pro_td_forecaster
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.6.4
  - flask=1.1.2
  - flask-cors=3.0.8
  - numpy=1.18.1
  - pandas=1.0.3
  - requests=2.23.0
  - scikit-learn=0.22.1
  - waitress=1.4.3