/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tdmanagement.views;

import exa2pro.BubbleChartForecasting;
import exa2pro.LineChartForecasting;
import exa2pro.Project;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Nikos
 */
public class JPanelForecasting extends javax.swing.JPanel {

    Project project;
    LineChartForecasting lineChartForecasting;
    BubbleChartForecasting bubbleChartForecasting;
    
    /**
     * Creates new form JPanelMetrics
     */
    public JPanelForecasting(Project project) {
        this.project= project;
        initComponents();
        
        jPanelFiles.setVisible(false);
        lineChartForecasting = new LineChartForecasting(project, 10);
        createAndAdd(false);
        
        jSliderHorizon.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                jLabelHorizon.setText(jSliderHorizon.getValue()+"");
            }
        });
        
        jSliderFiles.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                jLabelFiles.setText(jSliderFiles.getValue()+"");
            }
        });
    }

    private void createAndAdd(boolean bubble) {
        JPanel p;
        if(!bubble){
            p= lineChartForecasting.chartPanel;
            jLabelHorizon.setText(jSliderHorizon.getValue()+"");
        }
        else{
            p= bubbleChartForecasting.chartPanel;
            jLabelFiles.setText(jSliderFiles.getValue()+"");
        }
        javax.swing.GroupLayout jPanelChartLayout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanelChartLayout);
        jPanelChartLayout.setHorizontalGroup(
                jPanelChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelChartLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
        );
        jPanelChartLayout.setVerticalGroup(
                jPanelChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelChartLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
        );
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanelParent = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanelHorizon = new javax.swing.JPanel();
        jSliderHorizon = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabelHorizon = new javax.swing.JLabel();
        jPanelFiles = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFiles = new javax.swing.JLabel();
        jSliderFiles = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jSliderHorizon.setMajorTickSpacing(5);
        jSliderHorizon.setMinimum(1);
        jSliderHorizon.setPaintTicks(true);
        jSliderHorizon.setValue(10);
        jSliderHorizon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderHorizonMouseReleased(evt);
            }
        });

        jLabel1.setText("Horizon:");

        jLabelHorizon.setText("10");

        javax.swing.GroupLayout jPanelHorizonLayout = new javax.swing.GroupLayout(jPanelHorizon);
        jPanelHorizon.setLayout(jPanelHorizonLayout);
        jPanelHorizonLayout.setHorizontalGroup(
            jPanelHorizonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHorizonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabelHorizon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSliderHorizon, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHorizonLayout.setVerticalGroup(
            jPanelHorizonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSliderHorizon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelHorizonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabelHorizon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanelHorizon);

        jPanelFiles.setEnabled(false);

        jLabel2.setText("Files:");

        jLabelFiles.setText("0");

        jSliderFiles.setMajorTickSpacing(5);
        jSliderFiles.setMinimum(1);
        jSliderFiles.setPaintTicks(true);
        jSliderFiles.setValue(10);
        jSliderFiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSliderFilesMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelFilesLayout = new javax.swing.GroupLayout(jPanelFiles);
        jPanelFiles.setLayout(jPanelFilesLayout);
        jPanelFilesLayout.setHorizontalGroup(
            jPanelFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilesLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFiles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSliderFiles, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFilesLayout.setVerticalGroup(
            jPanelFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilesLayout.createSequentialGroup()
                .addComponent(jSliderFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel2.add(jPanelFiles);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelParentLayout = new javax.swing.GroupLayout(jPanelParent);
        jPanelParent.setLayout(jPanelParentLayout);
        jPanelParentLayout.setHorizontalGroup(
            jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1175, Short.MAX_VALUE)
        );
        jPanelParentLayout.setVerticalGroup(
            jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParentLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Files/Modules");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void jSliderHorizonMouseReleased(java.awt.event.MouseEvent evt) {                                             
        if(jButton1.getText().equals("Files/Modules")){
            jPanel1.removeAll();

            lineChartForecasting= new LineChartForecasting(project, jSliderHorizon.getValue());
            createAndAdd(false);
        }
        else{
            jPanel1.removeAll();
            
            bubbleChartForecasting= new BubbleChartForecasting(project, jSliderHorizon.getValue(), jSliderFiles.getValue());
            createAndAdd(true);
        }
	repaint();
    }                                            

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(jButton1.getText().equals("Files/Modules")){
            jButton1.setText("Project");
            jPanel1.removeAll();
            
            //create bubble plot
            jPanelFiles.setVisible(true);
            jSliderHorizon.setValue(10);
            jLabelHorizon.setText("10");
            jSliderFiles.setValue(10);
            jLabelFiles.setText("10");
            bubbleChartForecasting= new BubbleChartForecasting(project, jSliderHorizon.getValue(),jSliderFiles.getValue());
            createAndAdd(true);
            repaint();
        }
        else{
            jButton1.setText("Files/Modules");
            jPanel1.removeAll();
            
            //create chart
            jPanelFiles.setVisible(false);
            jSliderHorizon.setValue(10);
            jLabelHorizon.setText("10");
            lineChartForecasting= new LineChartForecasting(project, jSliderHorizon.getValue());
            createAndAdd(false);
            repaint();
        }
    }                                        

    private void jSliderFilesMouseReleased(java.awt.event.MouseEvent evt) {                                           
        jPanel1.removeAll();
        
        bubbleChartForecasting= new BubbleChartForecasting(project, jSliderHorizon.getValue(),jSliderFiles.getValue());
        createAndAdd(true);
	repaint();
    }                                          


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFiles;
    private javax.swing.JLabel jLabelHorizon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFiles;
    private javax.swing.JPanel jPanelHorizon;
    private javax.swing.JPanel jPanelParent;
    private javax.swing.JSlider jSliderFiles;
    private javax.swing.JSlider jSliderHorizon;
    // End of variables declaration                   

}
